// Abstract Algebra course — groups, rings, fields.
const ABSTRACTALG_COURSE = {
  id: "abstractalg",
  title: "Abstract Algebra",
  subtitle: "Groups, rings, fields, structures",
  emoji: "🧩",
  accent: "#9b59b6",
  accent2: "#5f27cd",
  description: "Five chapters on algebraic structures: groups, subgroups, homomorphisms, rings, and fields.",
  books: [
    {
      id: "aa1", num: 1, title: "Groups: Basics", subtitle: "Axioms, examples, subgroups",
      emoji: "🅖", accent: "#9b59b6", accent2: "#5f27cd",
      sections: [
        {
          title: "Group Axioms",
          questions: [
            { type: "regular", q: "How many group axioms?", answer: "4 (closure, associativity, identity, inverses).", solution: "Standard." },
            { type: "regular", q: "Is \\((\\mathbb{Z}, +)\\) a group?", answer: "Yes.", solution: "All axioms hold." },
            { type: "regular", q: "Is \\((\\mathbb{Z}, \\cdot)\\) a group?", answer: "No.", solution: "No inverses for most elements." },
            { type: "regular", q: "Identity in \\((\\mathbb{R}, +)\\)?", answer: "0.", solution: "\\(a + 0 = a\\)." },
            { type: "word", q: "Inverse of 5 in \\((\\mathbb{Q}^*, \\cdot)\\)?", answer: "1/5.", solution: "Multiplicative." }
          ]
        },
        {
          title: "Cyclic & Symmetric Groups",
          questions: [
            { type: "regular", q: "Cyclic group generated by a is denoted?", answer: "\\(\\langle a \\rangle\\).", solution: "Standard." },
            { type: "regular", q: "Order of element 2 in \\((\\mathbb{Z}_6, +)\\)?", answer: "3.", solution: "\\(2+2+2 = 0 \\bmod 6\\)." },
            { type: "regular", q: "\\(S_3\\) has order?", answer: "6.", solution: "\\(3! = 6\\)." },
            { type: "regular", q: "Is \\(S_3\\) abelian?", answer: "No.", solution: "Smallest non-abelian group." },
            { type: "word", q: "Identity in \\(S_n\\)?", answer: "The identity permutation.", solution: "Standard." }
          ]
        },
        {
          title: "Subgroups",
          questions: [
            { type: "regular", q: "Subgroup test: nonempty H ⊆ G is subgroup iff?", answer: "\\(ab^{-1} \\in H\\) for all a, b in H.", solution: "Standard test." },
            { type: "regular", q: "Trivial subgroup of G?", answer: "\\(\\{e\\}\\).", solution: "Identity only." },
            { type: "regular", q: "Subgroups of cyclic group are?", answer: "Cyclic.", solution: "Standard theorem." },
            { type: "regular", q: "\\(2\\mathbb{Z}\\) is a subgroup of?", answer: "\\((\\mathbb{Z}, +)\\).", solution: "Even integers." },
            { type: "word", q: "Number of subgroups of \\(\\mathbb{Z}_{12}\\)?", answer: "6 (one for each divisor of 12).", solution: "Standard." }
          ]
        }
      ],
      cumulativeTest: {
        title: "Cumulative Test — Group Basics",
        questions: [
          { type: "regular", q: "Group axioms include?", answer: "Closure, associativity, identity, inverses.", solution: "Standard." },
          { type: "regular", q: "Is \\((\\mathbb{N}, +)\\) a group?", answer: "No.", solution: "No inverses." },
          { type: "regular", q: "Order of \\(S_4\\)?", answer: "24.", solution: "\\(4!\\)." },
          { type: "regular", q: "Subgroup test condition?", answer: "\\(ab^{-1} \\in H\\).", solution: "Standard." },
          { type: "word", q: "Order of generator equals order of cyclic group. T/F?", answer: "True.", solution: "Standard." },
          { type: "word", q: "Identity of \\((\\mathbb{Q}^*, \\cdot)\\)?", answer: "1.", solution: "Standard." }
        ]
      }
    },
    {
      id: "aa2", num: 2, title: "Cosets & Quotient Groups", subtitle: "Lagrange and normal subgroups",
      emoji: "🔄", accent: "#5f27cd", accent2: "#9b59b6",
      sections: [
        {
          title: "Cosets",
          questions: [
            { type: "regular", q: "Left coset of H by a?", answer: "\\(aH = \\{ah : h \\in H\\}\\).", solution: "Standard." },
            { type: "regular", q: "Cosets of \\(2\\mathbb{Z}\\) in \\(\\mathbb{Z}\\)?", answer: "Evens and odds.", solution: "Standard." },
            { type: "regular", q: "Are cosets equal-size?", answer: "Yes.", solution: "Same as |H|." },
            { type: "regular", q: "Cosets partition the group. T/F?", answer: "True.", solution: "Equivalence relation." },
            { type: "word", q: "Coset eH equals?", answer: "H.", solution: "Identity coset." }
          ]
        },
        {
          title: "Lagrange's Theorem",
          questions: [
            { type: "regular", q: "Lagrange: |H| divides?", answer: "|G|.", solution: "Standard." },
            { type: "regular", q: "Index [G:H] = ?", answer: "|G|/|H|.", solution: "Number of cosets." },
            { type: "regular", q: "Possible subgroup orders of a group of order 6?", answer: "1, 2, 3, 6.", solution: "Divisors of 6." },
            { type: "regular", q: "If |G| = p prime, subgroups?", answer: "Only {e} and G.", solution: "Standard." },
            { type: "word", q: "Order of every element divides |G|. T/F?", answer: "True.", solution: "Lagrange corollary." }
          ]
        },
        {
          title: "Normal Subgroups & Quotient Groups",
          questions: [
            { type: "regular", q: "Normal subgroup definition?", answer: "\\(gHg^{-1} = H\\) for all g.", solution: "Standard." },
            { type: "regular", q: "Are all subgroups of abelian groups normal?", answer: "Yes.", solution: "Conjugation trivial." },
            { type: "regular", q: "Quotient group notation?", answer: "G/H.", solution: "Cosets as elements." },
            { type: "regular", q: "G/{e} = ?", answer: "G.", solution: "Trivial quotient." },
            { type: "word", q: "Why need normal for quotient?", answer: "So coset multiplication is well-defined.", solution: "Standard." }
          ]
        }
      ],
      cumulativeTest: {
        title: "Cumulative Test — Cosets & Quotients",
        questions: [
          { type: "regular", q: "Lagrange: |H| divides?", answer: "|G|.", solution: "Standard." },
          { type: "regular", q: "Cosets are equal-size?", answer: "Yes.", solution: "Same size as H." },
          { type: "regular", q: "Normal subgroup?", answer: "\\(gHg^{-1} = H\\).", solution: "Standard." },
          { type: "regular", q: "Index [G:H]?", answer: "|G|/|H|.", solution: "Standard." },
          { type: "word", q: "Subgroups of abelian groups are?", answer: "Normal.", solution: "Standard." },
          { type: "word", q: "Possible subgroup orders of |G| = 12?", answer: "1, 2, 3, 4, 6, 12.", solution: "Divisors." }
        ]
      }
    },
    {
      id: "aa3", num: 3, title: "Homomorphisms & Isomorphisms", subtitle: "Structure-preserving maps",
      emoji: "🪞", accent: "#48dbfb", accent2: "#5f27cd",
      sections: [
        {
          title: "Group Homomorphisms",
          questions: [
            { type: "regular", q: "Homomorphism property?", answer: "\\(\\phi(ab) = \\phi(a)\\phi(b)\\).", solution: "Standard." },
            { type: "regular", q: "Kernel definition?", answer: "\\(\\{g : \\phi(g) = e\\}\\).", solution: "Standard." },
            { type: "regular", q: "Image of identity?", answer: "Identity.", solution: "Always." },
            { type: "regular", q: "Kernel is what kind of subgroup?", answer: "Normal.", solution: "Standard." },
            { type: "word", q: "Is \\(\\phi: \\mathbb{Z} \\to \\mathbb{Z}, n \\mapsto 2n\\) a homomorphism?", answer: "Yes (additive).", solution: "\\(\\phi(a+b) = 2(a+b) = 2a + 2b\\)." }
          ]
        },
        {
          title: "Isomorphisms",
          questions: [
            { type: "regular", q: "Isomorphism = ?", answer: "Bijective homomorphism.", solution: "Standard." },
            { type: "regular", q: "\\(\\mathbb{Z}_4 \\cong \\mathbb{Z}_2 \\times \\mathbb{Z}_2\\)?", answer: "No.", solution: "Different structures (cyclic vs. Klein four)." },
            { type: "regular", q: "Isomorphic groups have same order. T/F?", answer: "True.", solution: "Bijection." },
            { type: "regular", q: "\\(\\mathbb{Z}_6 \\cong \\mathbb{Z}_2 \\times \\mathbb{Z}_3\\)?", answer: "Yes.", solution: "Standard." },
            { type: "word", q: "Both groups of order 4 up to iso: Z_4 and?", answer: "Klein four-group V.", solution: "Two iso classes." }
          ]
        },
        {
          title: "First Isomorphism Theorem",
          questions: [
            { type: "regular", q: "First isomorphism theorem statement?", answer: "\\(G/\\ker\\phi \\cong \\text{im}\\,\\phi\\).", solution: "Standard." },
            { type: "regular", q: "Image of homomorphism is a subgroup of?", answer: "Codomain.", solution: "Standard." },
            { type: "regular", q: "Trivial kernel implies?", answer: "Injection.", solution: "One-to-one." },
            { type: "regular", q: "Surjective + injective = ?", answer: "Bijection (isomorphism).", solution: "Standard." },
            { type: "word", q: "If φ: Z → Z_n by mod n, kernel?", answer: "nZ.", solution: "Standard." }
          ]
        }
      ],
      cumulativeTest: {
        title: "Cumulative Test — Homomorphisms",
        questions: [
          { type: "regular", q: "Homomorphism property?", answer: "\\(\\phi(ab) = \\phi(a)\\phi(b)\\).", solution: "Standard." },
          { type: "regular", q: "Kernel is what?", answer: "Normal subgroup.", solution: "Standard." },
          { type: "regular", q: "Isomorphism = ?", answer: "Bijective homomorphism.", solution: "Standard." },
          { type: "regular", q: "First iso theorem?", answer: "\\(G/\\ker \\cong \\text{im}\\).", solution: "Standard." },
          { type: "word", q: "Two non-iso groups of order 4?", answer: "\\(\\mathbb{Z}_4\\) and \\(V\\).", solution: "Standard." },
          { type: "word", q: "Trivial kernel means?", answer: "Injective.", solution: "Standard." }
        ]
      }
    },
    {
      id: "aa4", num: 4, title: "Rings", subtitle: "Two operations, ideals, quotients",
      emoji: "💍", accent: "#ee5253", accent2: "#ff9f43",
      sections: [
        {
          title: "Ring Basics",
          questions: [
            { type: "regular", q: "Ring requires?", answer: "Abelian group under +, semigroup under ·, distributive laws.", solution: "Standard." },
            { type: "regular", q: "Is \\(\\mathbb{Z}\\) a ring?", answer: "Yes.", solution: "Standard." },
            { type: "regular", q: "Commutative ring requires?", answer: "ab = ba.", solution: "Standard." },
            { type: "regular", q: "Ring with 1?", answer: "Has multiplicative identity.", solution: "Standard." },
            { type: "word", q: "Zero divisor?", answer: "Nonzero a with ab = 0 for some nonzero b.", solution: "Standard." }
          ]
        },
        {
          title: "Ideals",
          questions: [
            { type: "regular", q: "Ideal I of ring R requires?", answer: "Subring + absorbs multiplication from R.", solution: "Standard." },
            { type: "regular", q: "\\(n\\mathbb{Z}\\) is what in \\(\\mathbb{Z}\\)?", answer: "Ideal.", solution: "Standard." },
            { type: "regular", q: "Principal ideal (a)?", answer: "All multiples of a.", solution: "Standard." },
            { type: "regular", q: "Prime ideal: ab ∈ P implies?", answer: "a ∈ P or b ∈ P.", solution: "Standard." },
            { type: "word", q: "Maximal ideal in \\(\\mathbb{Z}\\)?", answer: "(p) for p prime.", solution: "Standard." }
          ]
        },
        {
          title: "Quotient Rings",
          questions: [
            { type: "regular", q: "Quotient ring notation?", answer: "R/I.", solution: "Standard." },
            { type: "regular", q: "\\(\\mathbb{Z}/n\\mathbb{Z}\\) = ?", answer: "\\(\\mathbb{Z}_n\\).", solution: "Standard." },
            { type: "regular", q: "Quotient by maximal ideal gives?", answer: "A field.", solution: "Standard." },
            { type: "regular", q: "Quotient by prime ideal gives?", answer: "An integral domain.", solution: "Standard." },
            { type: "word", q: "Z/(7) is a?", answer: "Field.", solution: "7 is prime." }
          ]
        }
      ],
      cumulativeTest: {
        title: "Cumulative Test — Rings",
        questions: [
          { type: "regular", q: "Ring requires?", answer: "Abelian group +, semigroup ·, distributive.", solution: "Standard." },
          { type: "regular", q: "\\(n\\mathbb{Z}\\) in \\(\\mathbb{Z}\\)?", answer: "Ideal.", solution: "Standard." },
          { type: "regular", q: "Quotient by maximal ideal?", answer: "Field.", solution: "Standard." },
          { type: "regular", q: "Quotient by prime ideal?", answer: "Integral domain.", solution: "Standard." },
          { type: "word", q: "Z/(p) for prime p?", answer: "Field.", solution: "Standard." },
          { type: "word", q: "Zero divisors in Z/(6)?", answer: "Yes (e.g. 2·3 = 0).", solution: "Standard." }
        ]
      }
    },
    {
      id: "aa5", num: 5, title: "Fields & Polynomial Rings", subtitle: "Field extensions, irreducibility",
      emoji: "🌐", accent: "#10ac84", accent2: "#48dbfb",
      sections: [
        {
          title: "Fields",
          questions: [
            { type: "regular", q: "Field = ?", answer: "Commutative ring where every nonzero element has multiplicative inverse.", solution: "Standard." },
            { type: "regular", q: "Examples of fields?", answer: "\\(\\mathbb{Q}, \\mathbb{R}, \\mathbb{C}, \\mathbb{Z}_p\\) (p prime).", solution: "Standard." },
            { type: "regular", q: "Is \\(\\mathbb{Z}\\) a field?", answer: "No.", solution: "No multiplicative inverses for most." },
            { type: "regular", q: "Characteristic of \\(\\mathbb{Z}_5\\)?", answer: "5.", solution: "Smallest n with n·1 = 0." },
            { type: "word", q: "Fields have only two ideals?", answer: "{0} and field itself.", solution: "Standard." }
          ]
        },
        {
          title: "Polynomial Rings",
          questions: [
            { type: "regular", q: "Polynomial ring notation over R?", answer: "R[x].", solution: "Standard." },
            { type: "regular", q: "Is \\(\\mathbb{Z}[x]\\) a field?", answer: "No.", solution: "Polynomials aren't invertible." },
            { type: "regular", q: "Irreducible polynomial over field?", answer: "Can't factor into lower-degree.", solution: "Standard." },
            { type: "regular", q: "Is \\(x^2 + 1\\) irreducible over \\(\\mathbb{R}\\)?", answer: "Yes.", solution: "No real roots." },
            { type: "word", q: "Is \\(x^2 - 2\\) irreducible over \\(\\mathbb{Q}\\)?", answer: "Yes.", solution: "\\(\\sqrt{2}\\) irrational." }
          ]
        },
        {
          title: "Field Extensions",
          questions: [
            { type: "regular", q: "F ⊆ E with E a field is called?", answer: "Field extension.", solution: "Standard." },
            { type: "regular", q: "Degree [E:F] = ?", answer: "Dim of E as F-vector space.", solution: "Standard." },
            { type: "regular", q: "Algebraic element satisfies?", answer: "Polynomial over F.", solution: "Standard." },
            { type: "regular", q: "\\([\\mathbb{C} : \\mathbb{R}]\\) = ?", answer: "2.", solution: "Basis {1, i}." },
            { type: "word", q: "Is \\(\\pi\\) algebraic over \\(\\mathbb{Q}\\)?", answer: "No.", solution: "Transcendental." }
          ]
        }
      ],
      cumulativeTest: {
        title: "Cumulative Test — Fields",
        questions: [
          { type: "regular", q: "Field requires?", answer: "Inverses for all nonzero.", solution: "Standard." },
          { type: "regular", q: "Is \\(\\mathbb{Z}_7\\) a field?", answer: "Yes.", solution: "7 prime." },
          { type: "regular", q: "Polynomial ring over R?", answer: "R[x].", solution: "Standard." },
          { type: "regular", q: "\\(x^2 + 1\\) over \\(\\mathbb{R}\\) irreducible?", answer: "Yes.", solution: "No real roots." },
          { type: "word", q: "\\([\\mathbb{C}:\\mathbb{R}]\\)?", answer: "2.", solution: "Standard." },
          { type: "word", q: "Examples of fields?", answer: "\\(\\mathbb{Q}, \\mathbb{R}, \\mathbb{C}\\).", solution: "Standard." }
        ]
      }
    }
  ]
};
